// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensorSensitivity3D.DAL;

namespace SensorSensitivity3D.DAL.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("SensorSensitivity3D.Domain.Entities.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DrawingIsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubstratePath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DrawingIsVisible = false,
                            Name = "Конфигурация 1",
                            SubstratePath = "C:\\Users\\Александер\\Documents\\GitHub\\SensorSensitivity3D\\SensorSensitivity3D\\Pioner.dxf"
                        },
                        new
                        {
                            Id = 2,
                            DrawingIsVisible = false,
                            Name = "Конфигурация 2",
                            SubstratePath = "C:\\Users\\Александер\\Documents\\GitHub\\SensorSensitivity3D\\SensorSensitivity3D\\Pioner.dxf"
                        },
                        new
                        {
                            Id = 3,
                            DrawingIsVisible = false,
                            Name = "Конфигурация 3",
                            SubstratePath = "C:\\Users\\Александер\\Documents\\GitHub\\SensorSensitivity3D\\SensorSensitivity3D\\Pioner.dxf"
                        });
                });

            modelBuilder.Entity("SensorSensitivity3D.Domain.Entities.Geophone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("GIsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoleNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsGood")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("R")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SIsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.Property<double>("Z")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId");

                    b.ToTable("Geophones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#460c09fa",
                            ConfigId = 3,
                            GIsVisible = false,
                            HoleNumber = 0,
                            IsGood = true,
                            Name = "Геофон 0",
                            R = 50,
                            SIsVisible = true,
                            X = -465.0,
                            Y = -1202.0,
                            Z = 197.0
                        },
                        new
                        {
                            Id = 2,
                            Color = "#46fbd91e",
                            ConfigId = 3,
                            GIsVisible = true,
                            HoleNumber = 1,
                            IsGood = true,
                            Name = "Геофон 1",
                            R = 50,
                            SIsVisible = false,
                            X = -775.0,
                            Y = -1079.0,
                            Z = 165.0
                        },
                        new
                        {
                            Id = 3,
                            Color = "#46514743",
                            ConfigId = 3,
                            GIsVisible = true,
                            HoleNumber = 2,
                            IsGood = true,
                            Name = "Геофон 2",
                            R = 50,
                            SIsVisible = false,
                            X = -616.0,
                            Y = -1117.0,
                            Z = 201.0
                        },
                        new
                        {
                            Id = 4,
                            Color = "#469996e1",
                            ConfigId = 2,
                            GIsVisible = true,
                            HoleNumber = 3,
                            IsGood = true,
                            Name = "Геофон 3",
                            R = 50,
                            SIsVisible = false,
                            X = -793.0,
                            Y = -1193.0,
                            Z = 160.0
                        },
                        new
                        {
                            Id = 5,
                            Color = "#46002bae",
                            ConfigId = 3,
                            GIsVisible = false,
                            HoleNumber = 4,
                            IsGood = true,
                            Name = "Геофон 4",
                            R = 50,
                            SIsVisible = true,
                            X = -529.0,
                            Y = -1129.0,
                            Z = 155.0
                        },
                        new
                        {
                            Id = 6,
                            Color = "#46841155",
                            ConfigId = 2,
                            GIsVisible = true,
                            HoleNumber = 5,
                            IsGood = true,
                            Name = "Геофон 5",
                            R = 50,
                            SIsVisible = false,
                            X = -780.0,
                            Y = -1242.0,
                            Z = 148.0
                        },
                        new
                        {
                            Id = 7,
                            Color = "#469f78ac",
                            ConfigId = 2,
                            GIsVisible = false,
                            HoleNumber = 6,
                            IsGood = true,
                            Name = "Геофон 6",
                            R = 50,
                            SIsVisible = false,
                            X = -535.0,
                            Y = -1087.0,
                            Z = 203.0
                        },
                        new
                        {
                            Id = 8,
                            Color = "#46b7207b",
                            ConfigId = 1,
                            GIsVisible = false,
                            HoleNumber = 7,
                            IsGood = true,
                            Name = "Геофон 7",
                            R = 50,
                            SIsVisible = false,
                            X = -768.0,
                            Y = -1119.0,
                            Z = 109.0
                        },
                        new
                        {
                            Id = 9,
                            Color = "#463c2b7b",
                            ConfigId = 3,
                            GIsVisible = true,
                            HoleNumber = 8,
                            IsGood = true,
                            Name = "Геофон 8",
                            R = 50,
                            SIsVisible = false,
                            X = -711.0,
                            Y = -1112.0,
                            Z = 139.0
                        },
                        new
                        {
                            Id = 10,
                            Color = "#4636b127",
                            ConfigId = 1,
                            GIsVisible = false,
                            HoleNumber = 9,
                            IsGood = true,
                            Name = "Геофон 9",
                            R = 50,
                            SIsVisible = false,
                            X = -779.0,
                            Y = -1110.0,
                            Z = 119.0
                        },
                        new
                        {
                            Id = 11,
                            Color = "#46d492c2",
                            ConfigId = 3,
                            GIsVisible = false,
                            HoleNumber = 10,
                            IsGood = true,
                            Name = "Геофон 10",
                            R = 50,
                            SIsVisible = false,
                            X = -541.0,
                            Y = -1216.0,
                            Z = 101.0
                        },
                        new
                        {
                            Id = 12,
                            Color = "#46f517ec",
                            ConfigId = 1,
                            GIsVisible = true,
                            HoleNumber = 11,
                            IsGood = true,
                            Name = "Геофон 11",
                            R = 50,
                            SIsVisible = true,
                            X = -622.0,
                            Y = -1155.0,
                            Z = 203.0
                        },
                        new
                        {
                            Id = 13,
                            Color = "#4675faff",
                            ConfigId = 3,
                            GIsVisible = false,
                            HoleNumber = 12,
                            IsGood = true,
                            Name = "Геофон 12",
                            R = 50,
                            SIsVisible = false,
                            X = -771.0,
                            Y = -1117.0,
                            Z = 152.0
                        },
                        new
                        {
                            Id = 14,
                            Color = "#46ee550a",
                            ConfigId = 3,
                            GIsVisible = true,
                            HoleNumber = 13,
                            IsGood = true,
                            Name = "Геофон 13",
                            R = 50,
                            SIsVisible = true,
                            X = -767.0,
                            Y = -1009.0,
                            Z = 191.0
                        },
                        new
                        {
                            Id = 15,
                            Color = "#469ae129",
                            ConfigId = 3,
                            GIsVisible = false,
                            HoleNumber = 14,
                            IsGood = true,
                            Name = "Геофон 14",
                            R = 50,
                            SIsVisible = false,
                            X = -549.0,
                            Y = -1135.0,
                            Z = 207.0
                        },
                        new
                        {
                            Id = 16,
                            Color = "#4641a014",
                            ConfigId = 1,
                            GIsVisible = false,
                            HoleNumber = 15,
                            IsGood = true,
                            Name = "Геофон 15",
                            R = 50,
                            SIsVisible = false,
                            X = -690.0,
                            Y = -1219.0,
                            Z = 151.0
                        },
                        new
                        {
                            Id = 17,
                            Color = "#46057340",
                            ConfigId = 2,
                            GIsVisible = true,
                            HoleNumber = 16,
                            IsGood = true,
                            Name = "Геофон 16",
                            R = 50,
                            SIsVisible = false,
                            X = -727.0,
                            Y = -1180.0,
                            Z = 120.0
                        },
                        new
                        {
                            Id = 18,
                            Color = "#46e6336c",
                            ConfigId = 1,
                            GIsVisible = true,
                            HoleNumber = 17,
                            IsGood = true,
                            Name = "Геофон 17",
                            R = 50,
                            SIsVisible = true,
                            X = -658.0,
                            Y = -1097.0,
                            Z = 106.0
                        },
                        new
                        {
                            Id = 19,
                            Color = "#464f3fdf",
                            ConfigId = 1,
                            GIsVisible = true,
                            HoleNumber = 18,
                            IsGood = true,
                            Name = "Геофон 18",
                            R = 50,
                            SIsVisible = false,
                            X = -486.0,
                            Y = -1117.0,
                            Z = 171.0
                        },
                        new
                        {
                            Id = 20,
                            Color = "#46c0a815",
                            ConfigId = 1,
                            GIsVisible = false,
                            HoleNumber = 19,
                            IsGood = true,
                            Name = "Геофон 19",
                            R = 50,
                            SIsVisible = true,
                            X = -678.0,
                            Y = -1020.0,
                            Z = 133.0
                        },
                        new
                        {
                            Id = 21,
                            Color = "#46bab0ab",
                            ConfigId = 2,
                            GIsVisible = false,
                            HoleNumber = 20,
                            IsGood = true,
                            Name = "Геофон 20",
                            R = 50,
                            SIsVisible = true,
                            X = -526.0,
                            Y = -1068.0,
                            Z = 101.0
                        },
                        new
                        {
                            Id = 22,
                            Color = "#460a50c6",
                            ConfigId = 2,
                            GIsVisible = true,
                            HoleNumber = 21,
                            IsGood = true,
                            Name = "Геофон 21",
                            R = 50,
                            SIsVisible = false,
                            X = -813.0,
                            Y = -1139.0,
                            Z = 204.0
                        },
                        new
                        {
                            Id = 23,
                            Color = "#4650196d",
                            ConfigId = 3,
                            GIsVisible = false,
                            HoleNumber = 22,
                            IsGood = true,
                            Name = "Геофон 22",
                            R = 50,
                            SIsVisible = true,
                            X = -488.0,
                            Y = -1007.0,
                            Z = 105.0
                        },
                        new
                        {
                            Id = 24,
                            Color = "#46fa69b3",
                            ConfigId = 1,
                            GIsVisible = false,
                            HoleNumber = 23,
                            IsGood = true,
                            Name = "Геофон 23",
                            R = 50,
                            SIsVisible = false,
                            X = -535.0,
                            Y = -1075.0,
                            Z = 204.0
                        },
                        new
                        {
                            Id = 25,
                            Color = "#46fb397a",
                            ConfigId = 1,
                            GIsVisible = false,
                            HoleNumber = 24,
                            IsGood = true,
                            Name = "Геофон 24",
                            R = 50,
                            SIsVisible = true,
                            X = -772.0,
                            Y = -1213.0,
                            Z = 192.0
                        },
                        new
                        {
                            Id = 26,
                            Color = "#4686d14a",
                            ConfigId = 2,
                            GIsVisible = false,
                            HoleNumber = 25,
                            IsGood = true,
                            Name = "Геофон 25",
                            R = 50,
                            SIsVisible = true,
                            X = -741.0,
                            Y = -1167.0,
                            Z = 163.0
                        },
                        new
                        {
                            Id = 27,
                            Color = "#4695a42a",
                            ConfigId = 2,
                            GIsVisible = false,
                            HoleNumber = 26,
                            IsGood = true,
                            Name = "Геофон 26",
                            R = 50,
                            SIsVisible = false,
                            X = -701.0,
                            Y = -1130.0,
                            Z = 167.0
                        },
                        new
                        {
                            Id = 28,
                            Color = "#4640fc2a",
                            ConfigId = 1,
                            GIsVisible = true,
                            HoleNumber = 27,
                            IsGood = true,
                            Name = "Геофон 27",
                            R = 50,
                            SIsVisible = true,
                            X = -614.0,
                            Y = -1249.0,
                            Z = 104.0
                        },
                        new
                        {
                            Id = 29,
                            Color = "#4691f232",
                            ConfigId = 1,
                            GIsVisible = true,
                            HoleNumber = 28,
                            IsGood = true,
                            Name = "Геофон 28",
                            R = 50,
                            SIsVisible = true,
                            X = -495.0,
                            Y = -1013.0,
                            Z = 178.0
                        },
                        new
                        {
                            Id = 30,
                            Color = "#46a79dd1",
                            ConfigId = 1,
                            GIsVisible = false,
                            HoleNumber = 29,
                            IsGood = true,
                            Name = "Геофон 29",
                            R = 50,
                            SIsVisible = true,
                            X = -545.0,
                            Y = -1195.0,
                            Z = 195.0
                        });
                });

            modelBuilder.Entity("SensorSensitivity3D.Domain.Entities.Geophone", b =>
                {
                    b.HasOne("SensorSensitivity3D.Domain.Entities.Configuration", "Configuration")
                        .WithMany()
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
